name: Test

on:
  push:
  workflow_dispatch:
    inputs:
      django:
        description: 'pip-installable package or git repository URL'
        required: true
        default: 'git+https://github.com/django/django.git@main#egg=Django'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        django:
          - "Django>=4.2,<5.0"
          - "git+https://github.com/django/django.git@stable/5.0.x#egg=Django"
          - "git+https://github.com/django/django.git@stable/5.1.x#egg=Django"
          - ${{ inputs.django ||'git+https://github.com/django/django.git@main#egg=Django' }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "${{ matrix.django }}"
      - name: Test
        run: |
          python manage.py test
